os:
  - linux

sudo: true

language: node_js

node_js: 4

addons:
  firefox: 46.0
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_script:
  - bower install

script:
  - xvfb-run npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
